spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-register: false
  instance:
    lease-renewal-interval-in-seconds: 0

