server:
  port: 443
spring:
  cloud:
    gateway:
      discovery: # 'server.webflux' no es una clave válida aquí
        locator:
          enabled: true
          # ELIMINA la línea 'lower-case-service-id: true'