server:
  port: 443

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              # Se omite 'lower-case-service-id: true' (por defecto es 'false')