server:
  port: 443

spring:
  cloud:
    gateway:
      server:
        webflux: 
          discovery:
            locator:
              enabled: true
              # Omitimos 'lower-case-service-id' para que use el default (false)
              # y coincida con tu servicio 'AUTH-SERVICE' en mayúsculas