server:
  port: 443
  
spring:
  cloud:
    gateway:
      # 1. Configuración del Discovery Locator (¡Correcto!)
      discovery:
        locator:
          enabled: true
          # El lower-case service-id es una buena práctica (opcional, pero recomendada)
          lower-case-service-id: true 
          
      # 2. Definición de Filtros Globales (La nueva sección)
      default-filters:
        # Usamos la sintaxis YAML de lista (el guion - ) para definir un filtro
        - RewritePath: 
            # Expresión regular para capturar la parte de la ruta después del nombre del servicio
            regexp: ^/.*?/(?<remaining>.*)$
            # Reemplazo, enviando solo la parte restante al microservicio
            replacement: /${remaining}          