server:
  port: 8081

spring:
  application:
    name: demogateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true





