server:
  port: 8080

spring:
  application:
    name: pokemonbreaker

  cloud:
    loadbalancer:
      eureka:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




